//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Input/InputController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputController: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputController"",
    ""maps"": [
        {
            ""name"": ""FocusMode"",
            ""id"": ""e3322b28-f42b-4a7e-a294-5653d646c753"",
            ""actions"": [
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""099fb550-e4d9-4252-8d37-d48a868a1149"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseDelta"",
                    ""type"": ""PassThrough"",
                    ""id"": ""866a426e-d7ba-4a79-846a-6eeaa219a601"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftClick"",
                    ""type"": ""Button"",
                    ""id"": ""53f836cc-30ac-439e-83d3-59a95715289a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""841dbef7-0467-4923-9820-88606f0cdbd3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""Button"",
                    ""id"": ""896c7e0f-ff3f-4c7a-8b59-9ffa79518e4f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MovementFly"",
                    ""type"": ""PassThrough"",
                    ""id"": ""14d03ebf-ec45-4789-8385-d6c3b8b5e3a7"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FastFly"",
                    ""type"": ""Button"",
                    ""id"": ""1b9f089e-214a-46d8-91ce-05bff7429834"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateFly"",
                    ""type"": ""PassThrough"",
                    ""id"": ""57e7d7dd-a486-4868-b4ea-7ebfe2ae80d8"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Options"",
                    ""type"": ""Button"",
                    ""id"": ""92f68dbf-549b-4ab8-bdef-8de0a7543030"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Y"",
                    ""id"": ""08bda854-b608-466f-a0e8-e234f7857b28"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""e6c1d3a7-c25c-4d37-bda5-d8eeb13e7667"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""7173cc63-6210-4931-b49c-fa1d9097479a"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""YVirtual"",
                    ""id"": ""24289cc1-dd91-4d6a-89f1-5b2c76c7f44d"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""e4e4215c-f07a-42cb-becb-326dddb5c207"",
                    ""path"": ""<VirtualMouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""98538185-68d6-4cda-aba6-4ca2f650c328"",
                    ""path"": ""<VirtualMouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""069f9471-0946-4ba9-a1e2-16c11bc0081e"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""MouseDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c22852ee-4106-49e3-b140-a74a8c2d5c50"",
                    ""path"": ""<VirtualMouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""MouseDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eca8f934-64b2-479a-affc-c2bf845f85f4"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""LeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3681f456-a11d-456c-b7dd-722fe897059f"",
                    ""path"": ""<VirtualMouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""LeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d47c4c9-d40d-4d6c-80fa-f93090a25f99"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dd76c03e-44dc-497e-b75d-ce3d56856d78"",
                    ""path"": ""<VirtualMouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5bdb273b-0a2a-4cfb-8e1e-5933e43fab14"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""44eb5284-e0eb-42ce-bb22-7481e608667c"",
                    ""path"": ""<VirtualMouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""3D Vector"",
                    ""id"": ""348dd72f-fe01-4a85-a4e1-9ee8b3b57d0a"",
                    ""path"": ""3DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementFly"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7eac5600-34e1-43a7-bf6e-8694533f8299"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""MovementFly"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9222e1f4-f806-4741-9b07-30c098a122ac"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""MovementFly"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""df1d145d-37d7-472b-a5fd-95da846aafe2"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""MovementFly"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0d119918-6310-4cfe-ad54-e93e31e1935e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""MovementFly"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""forward"",
                    ""id"": ""ce19a0bc-ec36-465f-919f-973886fe452c"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""MovementFly"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""backward"",
                    ""id"": ""1801a8b2-d71b-4928-be62-8c810c2d6fa9"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""MovementFly"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""91f411b7-cc27-432e-a4fb-e5ecff436ddb"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastFly"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""b91a8781-10e7-4421-bd96-66a55fe23e62"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateFly"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""f5d587a3-02ec-4681-b435-ee199868006e"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""RotateFly"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""da57d89c-0054-4a3f-91cf-b17e1945c8e7"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""RotateFly"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c48ffc96-7059-40cd-98cc-c977253dd43c"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Options"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""PC"",
            ""bindingGroup"": ""PC"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<VirtualMouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // FocusMode
        m_FocusMode = asset.FindActionMap("FocusMode", throwIfNotFound: true);
        m_FocusMode_Zoom = m_FocusMode.FindAction("Zoom", throwIfNotFound: true);
        m_FocusMode_MouseDelta = m_FocusMode.FindAction("MouseDelta", throwIfNotFound: true);
        m_FocusMode_LeftClick = m_FocusMode.FindAction("LeftClick", throwIfNotFound: true);
        m_FocusMode_MousePosition = m_FocusMode.FindAction("MousePosition", throwIfNotFound: true);
        m_FocusMode_RightClick = m_FocusMode.FindAction("RightClick", throwIfNotFound: true);
        m_FocusMode_MovementFly = m_FocusMode.FindAction("MovementFly", throwIfNotFound: true);
        m_FocusMode_FastFly = m_FocusMode.FindAction("FastFly", throwIfNotFound: true);
        m_FocusMode_RotateFly = m_FocusMode.FindAction("RotateFly", throwIfNotFound: true);
        m_FocusMode_Options = m_FocusMode.FindAction("Options", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // FocusMode
    private readonly InputActionMap m_FocusMode;
    private List<IFocusModeActions> m_FocusModeActionsCallbackInterfaces = new List<IFocusModeActions>();
    private readonly InputAction m_FocusMode_Zoom;
    private readonly InputAction m_FocusMode_MouseDelta;
    private readonly InputAction m_FocusMode_LeftClick;
    private readonly InputAction m_FocusMode_MousePosition;
    private readonly InputAction m_FocusMode_RightClick;
    private readonly InputAction m_FocusMode_MovementFly;
    private readonly InputAction m_FocusMode_FastFly;
    private readonly InputAction m_FocusMode_RotateFly;
    private readonly InputAction m_FocusMode_Options;
    public struct FocusModeActions
    {
        private @InputController m_Wrapper;
        public FocusModeActions(@InputController wrapper) { m_Wrapper = wrapper; }
        public InputAction @Zoom => m_Wrapper.m_FocusMode_Zoom;
        public InputAction @MouseDelta => m_Wrapper.m_FocusMode_MouseDelta;
        public InputAction @LeftClick => m_Wrapper.m_FocusMode_LeftClick;
        public InputAction @MousePosition => m_Wrapper.m_FocusMode_MousePosition;
        public InputAction @RightClick => m_Wrapper.m_FocusMode_RightClick;
        public InputAction @MovementFly => m_Wrapper.m_FocusMode_MovementFly;
        public InputAction @FastFly => m_Wrapper.m_FocusMode_FastFly;
        public InputAction @RotateFly => m_Wrapper.m_FocusMode_RotateFly;
        public InputAction @Options => m_Wrapper.m_FocusMode_Options;
        public InputActionMap Get() { return m_Wrapper.m_FocusMode; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FocusModeActions set) { return set.Get(); }
        public void AddCallbacks(IFocusModeActions instance)
        {
            if (instance == null || m_Wrapper.m_FocusModeActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FocusModeActionsCallbackInterfaces.Add(instance);
            @Zoom.started += instance.OnZoom;
            @Zoom.performed += instance.OnZoom;
            @Zoom.canceled += instance.OnZoom;
            @MouseDelta.started += instance.OnMouseDelta;
            @MouseDelta.performed += instance.OnMouseDelta;
            @MouseDelta.canceled += instance.OnMouseDelta;
            @LeftClick.started += instance.OnLeftClick;
            @LeftClick.performed += instance.OnLeftClick;
            @LeftClick.canceled += instance.OnLeftClick;
            @MousePosition.started += instance.OnMousePosition;
            @MousePosition.performed += instance.OnMousePosition;
            @MousePosition.canceled += instance.OnMousePosition;
            @RightClick.started += instance.OnRightClick;
            @RightClick.performed += instance.OnRightClick;
            @RightClick.canceled += instance.OnRightClick;
            @MovementFly.started += instance.OnMovementFly;
            @MovementFly.performed += instance.OnMovementFly;
            @MovementFly.canceled += instance.OnMovementFly;
            @FastFly.started += instance.OnFastFly;
            @FastFly.performed += instance.OnFastFly;
            @FastFly.canceled += instance.OnFastFly;
            @RotateFly.started += instance.OnRotateFly;
            @RotateFly.performed += instance.OnRotateFly;
            @RotateFly.canceled += instance.OnRotateFly;
            @Options.started += instance.OnOptions;
            @Options.performed += instance.OnOptions;
            @Options.canceled += instance.OnOptions;
        }

        private void UnregisterCallbacks(IFocusModeActions instance)
        {
            @Zoom.started -= instance.OnZoom;
            @Zoom.performed -= instance.OnZoom;
            @Zoom.canceled -= instance.OnZoom;
            @MouseDelta.started -= instance.OnMouseDelta;
            @MouseDelta.performed -= instance.OnMouseDelta;
            @MouseDelta.canceled -= instance.OnMouseDelta;
            @LeftClick.started -= instance.OnLeftClick;
            @LeftClick.performed -= instance.OnLeftClick;
            @LeftClick.canceled -= instance.OnLeftClick;
            @MousePosition.started -= instance.OnMousePosition;
            @MousePosition.performed -= instance.OnMousePosition;
            @MousePosition.canceled -= instance.OnMousePosition;
            @RightClick.started -= instance.OnRightClick;
            @RightClick.performed -= instance.OnRightClick;
            @RightClick.canceled -= instance.OnRightClick;
            @MovementFly.started -= instance.OnMovementFly;
            @MovementFly.performed -= instance.OnMovementFly;
            @MovementFly.canceled -= instance.OnMovementFly;
            @FastFly.started -= instance.OnFastFly;
            @FastFly.performed -= instance.OnFastFly;
            @FastFly.canceled -= instance.OnFastFly;
            @RotateFly.started -= instance.OnRotateFly;
            @RotateFly.performed -= instance.OnRotateFly;
            @RotateFly.canceled -= instance.OnRotateFly;
            @Options.started -= instance.OnOptions;
            @Options.performed -= instance.OnOptions;
            @Options.canceled -= instance.OnOptions;
        }

        public void RemoveCallbacks(IFocusModeActions instance)
        {
            if (m_Wrapper.m_FocusModeActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IFocusModeActions instance)
        {
            foreach (var item in m_Wrapper.m_FocusModeActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FocusModeActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public FocusModeActions @FocusMode => new FocusModeActions(this);
    private int m_PCSchemeIndex = -1;
    public InputControlScheme PCScheme
    {
        get
        {
            if (m_PCSchemeIndex == -1) m_PCSchemeIndex = asset.FindControlSchemeIndex("PC");
            return asset.controlSchemes[m_PCSchemeIndex];
        }
    }
    public interface IFocusModeActions
    {
        void OnZoom(InputAction.CallbackContext context);
        void OnMouseDelta(InputAction.CallbackContext context);
        void OnLeftClick(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
        void OnRightClick(InputAction.CallbackContext context);
        void OnMovementFly(InputAction.CallbackContext context);
        void OnFastFly(InputAction.CallbackContext context);
        void OnRotateFly(InputAction.CallbackContext context);
        void OnOptions(InputAction.CallbackContext context);
    }
}
